name: 🚀 Deploy para o InfinityFree

on:
  push:
    branches:
      - master # Se a sua branch principal se chamar 'main', mude aqui

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Baixando o código mais recente
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
      
    - name: 📂 Sincronizando arquivos via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /seudominio.com.br/htdocs/ # Substitua pelo seu domínio real configurado no InfinityFree
